module Commands
  TURN_NUM = 'TURN'
  HEARTBEAT = 'KATHUMP'

  ENTITY_CREATE = 'ENT_CREATE'
  ENTITY_MOVE = 'ENT_MOVE'
  ENTITY_MELEE_ATTACK = 'ENT_MELEE_ATTACK'
  ENTITY_GATHER = 'ENT_GATHER'

  PLAYER_JOIN = 'PLAYER_JOIN'

  # depricated
  ACK = 'ACK'
  NACK = 'NACK'
  CLIENT_CONNECT = 'CLIENT_CONNECT'
  CLIENT_DISCONNECT = 'DISCLIENT_CONNECT'
  SUCCESS = 'SUCCESS'
  FAILURE = 'FAILURE'
end
