module Commands
  TURN_NUM = 'TURN'
  HEARTBEAT = 'KATHUMP'

  ENTITY_REQ = 'ENT_REQ'
  ENTITY_MOVE = 'ENT_MOVE'
  ENTITY_ATTACK = 'ENT_ATTACK'

  PLAYER_JOIN = 'PLAYER_JOIN'

  # depricated
  ACK = 'ACK'
  NACK = 'NACK'
  CLIENT_CONNECT = 'CLIENT_CONNECT'
  CLIENT_DISCONNECT = 'DISCLIENT_CONNECT'
  SUCCESS = 'SUCCESS'
  FAILURE = 'FAILURE'
end
