class AnimationManager
  IMAGE_NAMES = {
    :unit_bird => {
      :selected => ['magiceffect0r.png'],
      :default => ['unit0r.png'],
      :nw => ['unit0r.png', 'unit1r.png', 'unit2r.png', 'unit3r.png', 
              'unit4r.png', 'unit5r.png', 'unit6r.png', 'unit7r.png'],
      :n => ['unit8r.png', 'unit9r.png', 'unit10r.png', 'unit11r.png', 
              'unit12r.png', 'unit13r.png', 'unit14r.png', 'unit15r.png'],
      :ne => ['unit16r.png', 'unit17r.png', 'unit18r.png', 'unit19r.png', 
              'unit20r.png', 'unit21r.png', 'unit22r.png', 'unit23r.png'],
      :e => ["unit24r.png","unit25r.png","unit26r.png","unit27r.png",
              "unit28r.png","unit29r.png","unit30r.png","unit31r.png"],
      :se => ["unit32r.png","unit33r.png","unit34r.png","unit35r.png",
              "unit36r.png","unit37r.png","unit38r.png","unit39r.png"],
      :s => ["unit40r.png","unit41r.png","unit42r.png","unit43r.png",
              "unit44r.png","unit45r.png","unit46r.png","unit47r.png"],
      :sw => ["unit48r.png","unit49r.png","unit50r.png","unit51r.png",
              "unit52r.png","unit53r.png","unit54r.png","unit55r.png"],
      :w => ["unit56r.png","unit57r.png","unit58r.png","unit59r.png",
              "unit60r.png","unit61r.png","unit62r.png","unit63r.png"]
    },
    :animal => {
      :selected => ['magiceffect0r.png'],
      :default => ['unit0r.png'],
      :nw => ['unit0r.png', 'unit1r.png', 'unit2r.png', 'unit3r.png', 
              'unit4r.png', 'unit5r.png', 'unit6r.png', 'unit7r.png'],
      :n => ['unit8r.png', 'unit9r.png', 'unit10r.png', 'unit11r.png', 
              'unit12r.png', 'unit13r.png', 'unit14r.png', 'unit15r.png'],
      :ne => ['unit16r.png', 'unit17r.png', 'unit18r.png', 'unit19r.png', 
              'unit20r.png', 'unit21r.png', 'unit22r.png', 'unit23r.png'],
      :e => ["unit24r.png","unit25r.png","unit26r.png","unit27r.png",
              "unit28r.png","unit29r.png","unit30r.png","unit31r.png"],
      :se => ["unit32r.png","unit33r.png","unit34r.png","unit35r.png",
              "unit36r.png","unit37r.png","unit38r.png","unit39r.png"],
      :s => ["unit40r.png","unit41r.png","unit42r.png","unit43r.png",
              "unit44r.png","unit45r.png","unit46r.png","unit47r.png"],
      :sw => ["unit48r.png","unit49r.png","unit50r.png","unit51r.png",
              "unit52r.png","unit53r.png","unit54r.png","unit55r.png"],
      :w => ["unit56r.png","unit57r.png","unit58r.png","unit59r.png",
              "unit60r.png","unit61r.png","unit62r.png","unit63r.png"]
    },
    :tree => {
      :selected => ['magiceffect0r.png'],
      :default => ['ressource2.png','ressource2.png','ressource2.png','ressource2.png','ressource2.png','ressource2.png','ressource2.png','ressource2.png']
    },
    :unit_worker => {
      :selected => ['magiceffect0r.png'],
      :default => ['unit96r.png'],
      :nw => ['unit64r.png', 'unit65r.png', 'unit66r.png', 'unit67r.png', 
              'unit68r.png', 'unit69r.png', 'unit70r.png', 'unit71r.png'],
      :n => ['unit72r.png', 'unit73r.png', 'unit74r.png', 'unit75r.png', 
              'unit76r.png', 'unit77r.png', 'unit78r.png', 'unit79r.png'],
      :ne => ['unit80r.png', 'unit81r.png', 'unit82r.png', 'unit83r.png', 
              'unit84r.png', 'unit85r.png', 'unit86r.png', 'unit87r.png'],
      :e => ["unit88r.png","unit89r.png","unit90r.png","unit91r.png",
              "unit92r.png","unit93r.png","unit94r.png","unit95r.png"],
      :se => ["unit96r.png","unit97r.png","unit98r.png","unit99r.png",
              "unit100r.png","unit101r.png","unit102r.png","unit103r.png"],
      :s => ["unit104r.png","unit105r.png","unit106r.png","unit107r.png",
              "unit108r.png","unit109r.png","unit110r.png","unit111r.png"],
      :sw => ["unit112r.png","unit113r.png","unit114r.png","unit115r.png",
              "unit116r.png","unit117r.png","unit118r.png","unit119r.png"],
      :w => ["unit120r.png","unit121r.png","unit122r.png","unit123r.png",
              "unit124r.png","unit125r.png","unit126r.png","unit127r.png"],
    },
    :structure_hospital => {
      :selected => ['magiceffect0r.png'],
      :default => ['hosp0b0.png'],
    },
  }
end
